// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEeYtawGJ9w-8yIKJ976pfy57CEs2IcLg',
    appId: '1:480354635303:web:1fb2f732c4993c08ce4802',
    messagingSenderId: '480354635303',
    projectId: 'elearningapp-8844c',
    authDomain: 'elearningapp-8844c.firebaseapp.com',
    storageBucket: 'elearningapp-8844c.appspot.com',
    measurementId: 'G-90HKL1DQQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4zynHb2O98doPfaf4RMyanKG9yQ-Dn3I',
    appId: '1:480354635303:android:98042138976ac862ce4802',
    messagingSenderId: '480354635303',
    projectId: 'elearningapp-8844c',
    storageBucket: 'elearningapp-8844c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0CYH8VEV5oaNWg_u9d3YL0IXXewlNLvE',
    appId: '1:480354635303:ios:809f9bcda691ff0dce4802',
    messagingSenderId: '480354635303',
    projectId: 'elearningapp-8844c',
    storageBucket: 'elearningapp-8844c.appspot.com',
    iosBundleId: 'com.elearningapp.workspaceFlutter',
  );
}
